version: "3.9"

services:
  redis:

    platform: linux/x86_64
    image: redis:7-alpine
    ports:
      - "6379:6379"
    command: redis-server --stop-writes-on-bgsave-error no
    volumes:
      - redis-data:/data
  mysql:
    platform: linux/x86_64
    image: mysql:8.4
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=tubescope
    volumes:
      - ./tmp/mysql:/var/lib/mysql
volumes:
  redis-data: